[project]
org-name = "ballerina"
version = "0.0.0"

[platform]
target = "java"

    [[platform.libraries]]
    artafactId = "auth"
    version = "@project.version@"
    path = "./lib/ballerina-auth-@project.version@.jar"
    groupId = "ballerina"
    modules = ["auth"]

    [[platform.libraries]]
    artafactId = "commons-logging"
    version = "1.1.1"
    path = "./lib/commons-logging-1.1.1.jar"
    groupId = "commons-logging"
    modules = ["auth"]
